ProjeSahaf/ProjeSahaf/Areas/Admin/Controllers/RolYonetimController.cs
using ProjeSahaf.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeSahaf.Areas.Admin.Models;

namespace ProjeSahaf.Areas.Admin.Controllers
{
    public class RolYonetimController : AdminController
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/RolYonetim
        public ActionResult Index()
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var model = roleManager.Roles.ToList();
            return View(model);
        }

        public ActionResult RolEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RolEkle(RolEkleModel rol)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            if(roleManager.RoleExists(rol.RolAd)==false)
            {
                roleManager.Create(new IdentityRole(rol.RolAd));
            }
            return RedirectToAction("Index");
        }

        public ActionResult RolKullaniciEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RolKullaniciEkle(RolKullaniciEkleModel model)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var kullanici = userManager.FindByName(model.KullaniciAdi);

            if (!userManager.IsInRole(kullanici.Id,model.RolAdi))
            {
                userManager.AddToRole(kullanici.Id, model.RolAdi);
            }

            
            return RedirectToAction("Index");
        }
    }
}

ProjeSahaf/ProjeSahaf/Areas/Admin/Views/RolYonetim/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<u1>
    @foreach (var item in Model)
    {
        <div class="form-group">
            <h3><li>@item.Name - @item.Users.Count</li></h3>
            </div>
           
            }
</u1>
<h2>@Html.ActionLink("Yeni Rol Ekle", "RolEkle")</h2>

ProjeSahaf/ProjeSahaf/Areas/Admin/Views/RolYonetim/RolEkle.cshtml
@model ProjeSahaf.Areas.Admin.Models.RolEkleModel
@{
    ViewBag.Title = "Rol Ekle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Rol Ekle</h2>

@using (Html.BeginForm("RolEkle", "RolYonetim", FormMethod.Post))
{
    @Html.TextBoxFor(m => m.RolAd)
    <input type="submit" value="Rol Ekle" class="btn btn-primary">
}

ProjeSahaf/ProjeSahaf/Areas/Admin/Views/RolYonetim/RolKullaniciEkle.cshtml
@model ProjeSahaf.Areas.Admin.Models.RolKullaniciEkleModel
@{
    ViewBag.Title = "RolKullaniciEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kullanıcı Rolü Ekle</h2>

@using (Html.BeginForm("RolKullaniciEkle", "RolYonetim", FormMethod.Post))
{<form class="form-horizontal" id="popup-validation">

        <div class="form-group">
            @Html.TextBoxFor(m => m.KullaniciAdi)
            <div class=" col-lg-4">
                @Html.LabelFor(m => m.KullaniciAdi)
            </div>
        </div>

        <div class="form-group">
            @Html.TextBoxFor(m => m.RolAdi)
            <div class=" col-lg-4">
                @Html.LabelFor(m => m.RolAdi)
            </div>
        </div>
     <div>
         <input type="submit" value="Ekle" class="btn btn-primary">
     </div>
    </form>
        }