ProjeSahaf/ProjeSahaf/Areas/Admin/Controllers/SliderController.cs
using ProjeSahaf.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeSahaf.Areas.Admin.Controllers
{
    
    public class SliderController : AdminController
    {
        ProjeB121210020EsraSehitoglu1CEntities1 db = new ProjeB121210020EsraSehitoglu1CEntities1();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var model = db.Slider.OrderByDescending(x => x.SliderID).ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        const string imageFolderPath = "/Content/images/slider-images/";
        public ActionResult AddSlider(SliderModel model)
        {

            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //Dosya Kaydetme
                if (model.Resim != null && model.Resim.ContentLength > 0)
                {
                    fileName = model.Resim.FileName;
                    var path = Path.Combine(Server.MapPath("~" + imageFolderPath), fileName);
                    model.Resim.SaveAs(path);

                }

                //EF nesnesi oluşturma.
                Slider slider = new Slider();

                slider.BaslangicTarihi = model.BaslangicTarihi;
                slider.BitisTarihi = model.BitisTarihi;
                slider.SliderBaslik = model.SliderBaslik;
                slider.SliderText = model.SliderText;
                slider.YazarAdi = model.YazarAdi;
                slider.Text = model.Text;
                slider.ResimYolu = imageFolderPath + fileName;

                db.Slider.Add(slider);
                db.SaveChanges();
            }

            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Slider model)
        {
            if (ModelState.IsValid) {
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProjeSahaf/ProjeSahaf/Areas/Admin/Views/Slider/Delete.cshtml
@model ProjeSahaf.Slider

@{
    ViewBag.Title = "Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>SİL</h2>
<h3>Silmek istediğinize emin misiniz?</h3>
</br>
@Model.SliderText
</br>
@Html.ActionLink("Kabul Ediyorum", "DeleteConfirm", new { id = Model.SliderID });
</br>
@Html.ActionLink("Kabul Etmiyorum", "Index");

ProjeSahaf/ProjeSahaf/Areas/Admin/Views/Slider/Edit.cshtml
@model ProjeSahaf.Slider

@{
    ViewBag.Title = "Düzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Slayt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SliderID)


        <div class="form-group">
            @Html.LabelFor(model => model.SliderText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BaslangicTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangicTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BaslangicTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BitisTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BitisTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYolu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYolu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYolu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SliderBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YazarAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YazarAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YazarAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

ProjeSahaf/ProjeSahaf/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
        
             
                        <div class="col-lg-6">
                          
                                <header>
                                    <h3><a>SLİDER EKLEME</a></h3>
                                    @*<div class="toolbar">
                                        <div class="btn-group">
                                            <a href="#defaultTable" data-toggle="collapse" class="btn btn-sm btn-default minimize-box">
                                                <i class="fa fa-angle-up"></i>
                                            </a>
                                            <a class="btn btn-danger btn-sm close-box"><i class="fa fa-times"></i></a>
                                        </div>
                                    </div>*@
                                </header>
                                @*<div id="defaultTable" class="body collapse in">*@
                                    <table class="table responsive-table">
                                        <thead>
                                            <tr>
                                    
                                                <th>ID</th>
                                                <th>Başlangıç Tarihi</th>
                                                <th>Bitiş Tarihi</th>
                                                <th>Kitap Adı</th>
                                                <th>Yazar Adı</th>
                                                <th>Kitap Bilgisi</th>
                                                <th>Resim Yolu</th>
                                                <th> </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.SliderID</td>
                                                    <td>@item.BaslangicTarihi</td>
                                                    <td>@item.BitisTarihi</td>
                                                    <td>@item.SliderBaslik</td>
                                                    <td>@item.YazarAdi</td>
                                                    <td>@item.SliderText</td>
                                                    <td>@item.ResimYolu</td>
                                                    <td>@Html.ActionLink("Düzenle","Edit","Slider", new { id = item.SliderID },null ) | @Html.ActionLink("Sil", "Delete", "Slider", new { id = item.SliderID }, null)</td>
                                                </tr>
                     

                                            }
                                            
                                        </tbody>
                                    </table>
                                </div>
                            @*</div>*@
               
                   