ProjeSahaf/ProjeSahaf/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ProjeSahaf.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Change(String languageSelect)
        {
            if (languageSelect != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageSelect);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(languageSelect);

            }

            HttpCookie cookie = new HttpCookie("language");
            cookie.Value = languageSelect;
            Response.Cookies.Add(cookie);
            return View("Index");
        }
    }
}

ProjeSahaf/ProjeSahaf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   
   
        @*<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    
    
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>*@
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <meta name="viewport" content="width=device-width">
    <title>@ViewBag.Title -Sahaf</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <noscript>
        <link rel="stylesheet" type="text/css" href="~/Content/css/noJS.css" />
    </noscript>
    <!-- Css Files End -->

</head>
<body>
    
    <!-- Start Main Wrapper -->
    <div class="wrapper">
        <!-- Start Main Header -->
        <!-- Start Top Nav Bar -->
        <section class="top-nav-bar">
            <section class="container-fluid container">
                <section class="row-fluid">
                    <section class="span6">
                        <ul class="top-nav">
                            <li>@Html.ActionLink(Resources.Home.anasayfa, "Index", "Home")</li>
                            <li>@Html.ActionLink(Resources.Home.online_magaza,"OnlineStore","Home")</li>
                            <li>@Html.ActionLink(Resources.Home.kitap_elestirileri, "BookReviews", "Home")</li>
                            <li><a href="shortcodes.html">@Resources.Home.yorumlar</a></li>
                            <li>@Html.ActionLink(Resources.Home.iletisim,"Contact","Home")</li>
                        </ul>
                    </section>
                    <section class="span6 e-commerce-list">
                        <ul>
                            <li>@Html.Partial("_LoginPartial")</li>
                            @*<li>Hoşgeldiniz! <a href="checkout.html">Giriş Yapın</a> ya da <a href="checkout.html">Üye Olun!</a></li>*@
                           
                            <li>@Html.ActionLink(Resources.Home.dil_secin, "Index", "Language")</li>
                        </ul>
                        <div class="c-btn">
                            <a href="cart.html" class="cart-btn">@Resources.Home.sepetim</a>
                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn btn-mini dropdown-toggle">0 item(s) - 0.00 ₺ <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                </ul>
                            </div>
                        </div>
                    </section>
                </section>
            </section>
        </section>
        <!-- End Top Nav Bar -->
        <header id="main-header">
            <section class="container-fluid container">
                <section class="row-fluid">
                    <section class="span4">
                        <h1 id="logo"> <a href="/Home/Index"><img src="~/Content/images/eebooks_logo.png" /></a> </h1>
                    </section>
                    <section class="span8">
                        <ul class="top-nav2">
                            @*<li><a href="checkout.html">Hesabım</a></li>
                            <li><a href="cart.html">Sepetim</a></li>
                            <li><a href="checkout.html">Checkout</a></li>
                            <li><a href="order-recieved.html">Track Your Order</a></li>*@
                        </ul>
                        <div class="search-bar">
                            <input name="" type="text" value="@Resources.Home.ara1" />
                            <input name="" type="button" value="@Resources.Home.ara" />
                        </div>
                    </section>
                </section>
            </section>
            <!-- Start Main Nav Bar -->
            <nav id="nav">
                <div class="navbar navbar-inverse">
                    <div class="navbar-inner">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                        <div class="nav-collapse collapse">
                            <ul class="nav">
                                <li>@Html.ActionLink(Resources.Home.online_magaza, "OnlineStore", "Home")</li>
                                <li><a href="grid-view.html">@Resources.Home.kiralik_kitap</a></li>
                                <li><a href="grid-view.html">@Resources.Home.yazarlar</a></li>
                                <li><a href="grid-view.html">@Resources.Home.yayinevleri</a></li>
                                <li><a href="grid-view.html">@Resources.Home.kategoriler</a></li>
                                <li><a href="grid-view.html">@Resources.Home.koleksiyonlar</a></li>
                               
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                    <!-- /.navbar-inner -->
                </div>
                <!-- /.navbar -->
            </nav>
            <!-- End Main Nav Bar -->
        </header>
        <!-- End Main Header -->
@RenderBody()
        <!-- Start Footer Top 2 -->
        <section class="container-fluid footer-top2">
            <section class="social-ico-bar">
                <section class="container">
                    <section class="row-fluid">
                        <div id="socialicons" class="hidden-phone"> <a id="social_linkedin" class="social_active" href="#" title="Visit Google Plus page"><span></span></a> <a id="social_facebook" class="social_active" href="#" title="Visit Facebook page"><span></span></a> <a id="social_twitter" class="social_active" href="#" title="Visit Twitter page"><span></span></a> <a id="social_youtube" class="social_active" href="#" title="Visit Youtube"><span></span></a> <a id="social_vimeo" class="social_active" href="#" title="Visit Vimeo"><span></span></a> <a id="social_trumblr" class="social_active" href="#" title="Visit Vimeo"><span></span></a> <a id="social_google_plus" class="social_active" href="#" title="Visit Vimeo"><span></span></a> <a id="social_dribbble" class="social_active" href="#" title="Visit Vimeo"><span></span></a> <a id="social_pinterest" class="social_active" href="#" title="Visit Vimeo"><span></span></a> </div>
                        <ul class="footer2-link">
                            <li><a href="about-us.html">About Us</a></li>
                            <li><a href="contact.html">Customer Service</a></li>
                            <li><a href="order-recieved.html">Orders Tracking</a></li>
                        </ul>
                    </section>
                </section>
            </section>

            <section class="container">
                <section class="row-fluid">

                    @{Html.RenderAction("_BestSellers", "Home"); }
                    @{Html.RenderAction("_TopRated", "Home"); }


                    <figure class="span4">
                        <h4>From the blog</h4>
                        <ul class="f2-pots-list">
                            <li> <span class="post-date2">28 APR</span> <a href="blog-detail.html">Corso completo di grafica web completo di grafi dare...</a> <span class="comments-num">6 comments</span> </li>
                            <li> <span class="post-date2">28 APR</span> <a href="blog-detail.html">Corso completo di grafica web completo di grafi dare...</a> <span class="comments-num">6 comments</span> </li>
                            <li> <span class="post-date2">28 APR</span> <a href="blog-detail.html">Corso completo di grafica web completo di grafi dare...</a> <span class="comments-num">6 comments</span> </li>
                        </ul>
                    </figure>
                </section>
            </section>
        </section>
        <!-- End Footer Top 2 -->
        <!-- Start Main Footer -->
        <footer id="main-footer">
            <section class="social-ico-bar">
                <section class="container">
                    <section class="row-fluid">
                        <article class="span6">
                            <p>© 2016 EEBooks </p>
                        </article>
                        <article class="span6 copy-right">
                            <p>Designed by Esra ŞEHİTOĞLU</p>
                        </article>
                    </section>
                </section>
            </section>
        </footer>
        <!-- End Main Footer -->
    </div>
    <!-- End Main Wrapper -->
    <!-- JS Files Start -->


    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/jqueryval")*@
   
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
  
   

    <script type="text/javascript">
	    $(function () {
	        $("#mybook").booklet({
				width:'100%',
				height:430,
				auto: true,
				//speed: 250,
			});
	    });
    </script>
    <!-- JS Files End -->
    <noscript>
        <style>
            #socialicons > a span {
                top: 0px;
                left: -100%;
                -webkit-transition: all 0.3s ease;
                -moz-transition: all 0.3s ease-in-out;
                -o-transition: all 0.3s ease-in-out;
                -ms-transition: all 0.3s ease-in-out;
                transition: all 0.3s ease-in-out;
            }

            #socialicons > ahover div {
                left: 0px;
            }
        </style>
    </noscript>

    <script type="text/javascript">
  /* <![CDATA[ */
  $(document).ready(function() {
  $('.social_active').hoverdir( {} );
})
/* ]]> */
    </script>

    
    @RenderSection("scripts", required: false)
</body>
</html>